apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rate-limits-exporter.fullname" . }}
  labels:
    {{- include "rate-limits-exporter.labels" . | nindent 4 }}
data:
  dockerhub_username: {{ .Values.app.dockerhub_username | b64enc }}
  dockerhub_password: {{ .Values.app.dockerhub_password | b64enc }}
