name: 'Release'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

env:
  HELM_DOCS_VERSION: v1.14.2

jobs:
  helm-docs:
    name: 'Generate Helm documentation'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Generate chart documentation'
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:${HELM_DOCS_VERSION}

      - name: 'Upload documentation for next job'
        uses: actions/upload-artifact@v4
        with:
          name: readme
          path: chart/README.md
          retention-days: 1

  release:
    name: 'Release'
    runs-on: ubuntu-22.04
    container: node:20-bullseye
    env:
      GITHUB_TOKEN: ${{ github.token }}
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Install and Configure applications'
        run: |
          apt-get update
          apt-get install -yqq --no-install-recommends \
            ca-certificates \
            git-core

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # fix for github hosted runners
      - name: 'Add git path to trusted'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: 'Download docs from previous job'
        uses: actions/download-artifact@v4
        with:
          name: readme
          path: chart/

      - name: 'Release'
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@4.6.3
