name: 'Test chart'

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

env:
  HELM_VERSION: v3.15.2
  KUBERNETES_CLUSTER_VERSION: v1.28.9
  KIND_VERSION: v0.23.0
  KUBE_SCORE_VERSION: v1.18.0
  KUBE_CONFORM_VERSION: 0.6.7
  CHART_NAME: rate-limits-exporter
  NAMESPACE: awesome-app

jobs:
  test-chart:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Checkout server repository'
        uses: actions/checkout@v4

      - name: 'Install Kubeconform'
        uses: bmuschko/setup-kubeconform@v1
        with:
          kubeconform-version: ${{ env.KUBE_CONFORM_VERSION }}

      - name: 'Install Helm'
        uses: azure/setup-helm@v4.2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: 'Install kubectl'
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBERNETES_CLUSTER_VERSION }}

      - name: 'Install kind and create Kubernetes cluster'
        uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:${{ env.KUBERNETES_CLUSTER_VERSION }}

      - name: 'Install kube-score'
        run: |
          curl -Lo ./kube-score.tar.gz https://github.com/zegl/kube-score/releases/download/${KUBE_SCORE_VERSION}/kube-score_${KUBE_SCORE_VERSION//v}_linux_amd64.tar.gz
          tar -xf kube-score.tar.gz
          chmod +x kube-score
          sudo mv kube-score /usr/local/bin/

      - name: 'Run Helm lint'
        run: |
          helm lint chart

      - name: 'Run Kubeconform'
        run: |
          helm template . | kubeconform -kubernetes-version ${KUBERNETES_CLUSTER_VERSION//v} -summary -strict -verbose -

      - name: 'Run kube-score checks'
        working-directory: chart
        run: |
          helm template . | kube-score score -

      - name: 'Run Helm tests'
        working-directory: chart
        run: |
          helm upgrade \
            --install \
            --namespace ${NAMESPACE} \
            --create-namespace \
            --wait \
            ${CHART_NAME} .

          helm --namespace ${NAMESPACE} \
            test ${CHART_NAME}
